### ISSUE TITLE
error: cannot derive coordinates from non-numeric matrix

### ISSUE THREAD

**Issue by rjnskl** [environmentalinformatics-marburg/GSODTools#3]
I'm trying to run the example code for filtering stations
```
shp_kibo <- stationFromCoords(x = 37.359031, y = -3.065053, width = 500)
```

but invariably get this error:
```
Error in .local(obj, ...) : 
  cannot derive coordinates from non-numeric matrix
```

Any thoughts on why, or ways around it? Are there other libraries I should have installed to get this to work? 

thanks!

**Comment by fdetsch** [comment]
Fixed with 75f74d678f48a84038af85594b2e3a72065c6ab7. You'll likely encounter more such bugs as you progress through the package. Feel free to report!
