### ISSUE TITLE
Error in CRS("+init=epsg:4326") : NA

### ISSUE THREAD

**Issue by jimoreira** [environmentalinformatics-marburg/GSODTools#5]
HI, 
Nice Package, trying to use it, i have the error mentioned on the title when running:

`
gsod_shp <- gsodReformat(data = gsodstations,
                          elevation = TRUE, 
                          coords = TRUE,
                          rm_invalid_coords = TRUE,
                          df2sp = TRUE)
`

do you have any ideas why?? 

thanks!

**Comment by jimoreira** [comment]
solve it this way: 

`
proj4string(data.lonlat) <- sp::CRS(sf::st_crs(4326)[[2]])

`
thanks

**Comment by fdetsch** [comment]
Thanks, can you try again with the latest version on branch `5-error-in-crs`?

```r
remotes::install_github(
  "environmentalinformatics-marburg/GSODTools"
  , ref = "5-error-in-crs"
)
```
